package minefall.libs;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;

public class MCMod {

    @Mod.Metadata
    public static ModMetadata metadata;

    public static void MetaMcMod(){

        metadata.autogenerated = false;
        metadata.authorList.add("The UniversalTeam");
        metadata.credits = "Created by UniversalRed and the UniversalTeam";
        metadata.description = "Standby for MineFall, Bringing Titans To Life";
    }

}
